version: '3'

services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:mariadb://<Endpoint>:3306/jokedb
      DB_USERNAME: jokedbuser
      DB_PASSWORD: 12345678
